(() => {
	'use strict';
	const API = localStorage.getItem('chirp_api_url') || 'http://localhost:8080';
	const state = { auth: JSON.parse(localStorage.getItem('chirp_auth') || 'null'), posts: [], page: 'home', viewedUserId: null };
	const $ = (s) => document.querySelector(s);
	const esc = (v = '') => String(v).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
	const initials = (name = '?') => name.trim().split(/\s+/).slice(0, 2).map((p) => p[0]).join('').toUpperCase() || '?';
	const date = (v) => v ? new Date(v).toLocaleString([], { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }) : 'just now';
	const user = () => state.auth && { id:state.auth.userId, username:state.auth.username };
	async function request(path, options = {}) {
		const headers = { 'Content-Type':'application/json', ...(options.headers || {}) };
		if (state.auth?.token) headers.Authorization = `${state.auth.tokenType || 'Bearer'} ${state.auth.token}`;
		const response = await fetch(`${API}${path}`, { ...options, headers }); const text = await response.text(); let data = text;
		try { data = text ? JSON.parse(text) : null; } catch (_) { /* text response */ }
		if (response.status === 401) { logout(false); throw new Error('Your session expired. Please sign in again.'); }
		if (!response.ok) throw new Error(data?.message || data?.error || text || `Request failed (${response.status})`); return data;
	}
	function toast(message) { const root = $('#toast-root'); root.innerHTML = `<div class="toast">${esc(message)}</div>`; setTimeout(() => { root.innerHTML = ''; }, 3200); }
	function avatar(u = {}) { return `<div class="avatar">${u.profilePicture ? `<img src="${esc(u.profilePicture)}" alt="">` : esc(initials(u.displayName || u.username))}</div>`; }
	function render() {
		if (!state.auth) { $('#app').innerHTML = `<div class="modal-backdrop"><section class="modal"><h2>Welcome to Chirp</h2><p>Share your thoughts with the world.</p><div class="form-actions"><button class="secondary" data-action="auth" data-mode="login">Sign in</button><button class="primary" data-action="auth" data-mode="register">Create account</button></div></section></div>`; return; }
		$('#app').innerHTML = `<div class="shell"><aside class="sidebar"><a class="brand" href="#" data-action="home">chirp</a><nav class="nav"><button data-action="home"><span>⌂</span>Home</button><button data-action="notifications"><span>♧</span>Notifications <b id="notification-badge"></b></button><button data-action="profile"><span>◎</span>Profile</button><button data-action="logout"><span>↪</span>Log out</button></nav><div class="user-chip">${avatar(user())}<div class="user-meta"><strong>${esc(user().username)}</strong><small>@${esc(user().username)}</small></div></div></aside><main><header class="topbar"><h1>${state.page === 'profile' ? 'Profile' : state.page === 'notifications' ? 'Notifications' : state.page === 'connections' ? 'Connections' : 'Home'}</h1><button class="icon-btn" data-action="refresh">↻</button></header>${state.page === 'home' ? composer() : ''}<section id="content"><div class="loading">Loading…</div></section></main><aside class="rightbar"><div class="search">⌕ <input id="search" placeholder="Search users" autocomplete="off"></div><div id="search-results"></div><div class="panel"><h2>What's happening</h2><p>Stay curious. Stay kind.</p><small>Connected to ${esc(API)}</small></div></aside></div>`;
		loadPage();
		refreshNotificationBadge();
	}
	function composer() { return `<section class="composer">${avatar(user())}<div class="composer-body"><textarea id="post-content" maxlength="280" placeholder="What is happening?!"></textarea><div class="composer-footer"><span class="counter" id="counter">0 / 280</span><button class="primary" data-action="post" disabled>Chirp</button></div></div></section>`; }
	async function loadPage() { try { if (state.page === 'home') await loadPosts(); else if (state.page === 'profile') await loadProfile(); else if (state.page === 'connections') await loadConnections(); else await loadNotifications(); } catch (e) { $('#content').innerHTML = `<div class="feed-empty">${esc(e.message)}<br><button class="secondary" data-action="refresh">Try again</button></div>`; } }
	async function loadPosts() { let posts = await request(`/api/users/${state.auth.userId}/posts/feed`); if (!Array.isArray(posts)) posts = await request(`/api/users/${state.auth.userId}/posts`); state.posts = posts || []; $('#content').innerHTML = postList(state.posts); }
	async function loadProfile() { const profileId = state.viewedUserId || state.auth.userId; const p = await request(`/api/users/${profileId}`); const posts = await request(`/api/users/${profileId}/posts`); const followers = await request(`/api/users/${profileId}/follows/followers`); const followingUsers = await request(`/api/users/${profileId}/follows/following`); state.posts = posts || []; let edit = '<button class="secondary" data-action="edit-profile">Edit profile</button>'; if (profileId != state.auth.userId) { const following = await request(`/api/users/${state.auth.userId}/follows/${profileId}/status`); edit = followButton(profileId, following); } $('#content').innerHTML = `<section class="panel profile-panel" style="margin:0;border-radius:0;background:#fff;padding:28px"><div style="display:flex;gap:16px;align-items:center">${avatar(p)}<div style="flex:1"><h2 style="margin:0">${esc(p.displayName || p.username)}</h2><p style="margin:2px 0;color:var(--muted)">@${esc(p.username)}</p></div>${edit}</div><p>${esc(p.bio || 'No bio yet.')}</p><div class="profile-stats"><button data-action="connections" data-type="followers" data-user-id="${profileId}"><strong>${followers.length}</strong><span>Followers</span></button><button data-action="connections" data-type="following" data-user-id="${profileId}"><strong>${followingUsers.length}</strong><span>Following</span></button><span><strong>${state.posts.length}</strong><span>Posts</span></span></div></section>` + postList(state.posts); }
	async function loadConnections() { const profileId = state.viewedUserId || state.auth.userId; const type = state.connectionType || 'followers'; const profile = await request(`/api/users/${profileId}`); const list = await request(`/api/users/${profileId}/follows/${type}`); const title = type === 'followers' ? 'Followers' : 'Following'; const cards = (list || []).map((item) => { const person = item.user || {}; return `<div class="connection-card">${avatar(person)}<button class="connection-user" data-action="view-profile" data-id="${person.id}"><strong>${esc(person.displayName || person.username)}</strong><small>@${esc(person.username)}</small></button>${person.id == state.auth.userId ? '' : `<button class="follow-btn" data-action="follow" data-id="${person.id}">Follow</button>`}</div>`; }).join('') || '<div class="feed-empty">No users here yet.</div>'; $('#content').innerHTML = `<div class="connections-header"><button class="icon-btn" data-action="back-profile">←</button><div><h2>${title}</h2><small>@${esc(profile.username)}</small></div></div><section class="connections-list">${cards}</section>`; }
	function followButton(id, following) { return `<button class="primary" data-action="follow" data-id="${id}" data-following="${Boolean(following)}">${following ? 'Unfollow' : 'Follow'}</button>`; }
	function postList(posts) { return posts.length ? posts.map(postCard).join('') : '<div class="feed-empty">No posts yet. Be the first to chirp!</div>'; }
	function postCard(post) { const a = post.author || {}; return `<article class="post" data-post-id="${post.id}">${avatar(a)}<div class="post-content"><div class="post-head"><button class="profile-link" data-action="view-profile" data-id="${a.id}"><strong>${esc(a.displayName || a.username || 'User')}</strong><span>@${esc(a.username || '')}</span></button><span>·</span><span>${date(post.createdAt)}</span></div><div class="post-text">${esc(post.content)}</div><div class="post-actions"><button class="action comment" data-action="comments" data-id="${post.id}">💬 ${post.commentCount || 0}</button><button class="action ${post.likedByCurrentUser ? 'liked' : ''}" data-action="like" data-id="${post.id}">${post.likedByCurrentUser ? '♥' : '♡'} ${post.likeCount || 0}</button>${a.id == state.auth.userId ? `<button class="action" data-action="delete" data-id="${post.id}">⌫</button>` : ''}</div><div class="comments hidden" id="comments-${post.id}"></div></div></article>`; }
	async function createPost() { const content = $('#post-content').value.trim(); if (!content) return; try { await request(`/api/users/${state.auth.userId}/posts/create`, { method:'POST', body:JSON.stringify({ content }) }); $('#post-content').value = ''; toast('Your chirp is live!'); await loadPosts(); } catch (e) { toast(e.message); } }
	async function toggleLike(id, button) { if (button.dataset.busy === 'true') return; button.dataset.busy = 'true'; try { const liked = Boolean(await request(`/api/users/${state.auth.userId}/posts/${id}/like/toggle`, { method:'POST' })); const post = state.posts.find((p) => p.id == id); const oldCount = post ? Number(post.likeCount || 0) : Number(button.dataset.count || 0); const count = Math.max(0, oldCount + (liked ? 1 : -1)); if (post) { post.likedByCurrentUser = liked; post.likeCount = count; } button.dataset.count = count; button.classList.toggle('liked', liked); button.innerHTML = `${liked ? '♥' : '♡'} ${count}`; toast(liked ? 'Liked' : 'Like removed'); } catch (e) { toast(e.message); } finally { button.dataset.busy = 'false'; } }
	async function comments(id) { const box = $(`#comments-${id}`); box.classList.toggle('hidden'); if (box.dataset.loaded) return; try { const list = await request(`/api/users/${state.auth.userId}/posts/${id}/comments`); box.innerHTML = (list || []).map((c) => `<p><strong>@${esc(c.username)}</strong> ${esc(c.content)} <small>${date(c.createdAt)}</small></p>`).join('') + `<form class="comment-form"><input placeholder="Write a reply…"><button class="primary">Send</button></form>`; box.dataset.loaded = 'true'; box.querySelector('form').onsubmit = async (event) => { event.preventDefault(); const input = event.target.querySelector('input'); if (!input.value.trim()) return; try { await request(`/api/users/${state.auth.userId}/posts/${id}/comments/create`, { method:'POST', body:JSON.stringify({ content:input.value.trim() }) }); const post = state.posts.find((p) => p.id == id); if (post) post.commentCount = (post.commentCount || 0) + 1; const commentButton = document.querySelector(`[data-action="comments"][data-id="${id}"]`); if (commentButton) commentButton.innerHTML = `💬 ${(post && post.commentCount) || 1}`; box.dataset.loaded = ''; box.classList.add('hidden'); toast('Reply added'); await refreshNotificationBadge(); } catch (e) { toast(e.message); } }; } catch (e) { box.innerHTML = `<small>${esc(e.message)}</small>`; } }
	async function loadNotifications() { const list = await request(`/api/users/${state.auth.userId}/notifications`); $('#content').innerHTML = `<div style="padding:10px 18px;text-align:right"><button class="secondary" data-action="read-all">Mark all as read</button></div>` + ((list || []).map((n) => `<div class="notification" style="padding:18px;border-bottom:1px solid var(--line)">${avatar(n.sender)} <strong>@${esc(n.sender?.username || 'Someone')}</strong> ${esc(String(n.type || '').toLowerCase())} your post. <small>${date(n.createdAt)}</small></div>`).join('') || '<div class="feed-empty">No notifications yet.</div>'); }
	async function follow(id, button) { if (button.dataset.busy === 'true') return; button.dataset.busy = 'true'; const following = button.dataset.following === 'true'; try { const nowFollowing = Boolean(await request(`/api/users/${state.auth.userId}/follows/${id}/toggle`, { method:'POST' })); button.dataset.following = String(nowFollowing); button.textContent = nowFollowing ? 'Unfollow' : 'Follow'; toast(nowFollowing ? 'Following user' : 'Unfollowed user'); if (state.page === 'profile' && state.viewedUserId == id) loadProfile(); } catch (error) { toast(error.message); } finally { button.dataset.busy = 'false'; } }
	async function refreshNotificationBadge() { const badge = $('#notification-badge'); if (!badge || !state.auth) return; try { const count = await request(`/api/users/${state.auth.userId}/notifications/unread-count`); badge.textContent = Number(count) > 0 ? `(${count})` : ''; } catch (_) { badge.textContent = ''; } }
	async function editProfile() { try { const profile = await request(`/api/users/${state.auth.userId}`); $('#modal-root').innerHTML = `<div class="modal-backdrop"><section class="modal"><h2>Edit profile</h2><form class="form" id="profile-form"><div><label>Display name</label><input name="displayName" value="${esc(profile.displayName || '')}"></div><div><label>Bio</label><textarea name="bio" maxlength="160" style="border:1px solid var(--line);padding:10px;min-height:90px">${esc(profile.bio || '')}</textarea></div><div><label>Profile picture URL</label><input name="profilePicture" value="${esc(profile.profilePicture || '')}"></div><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">Save changes</button></div></form></section></div>`; $('#profile-form').onsubmit = async (e) => { e.preventDefault(); try { await request(`/api/users/${state.auth.userId}/update`, { method:'PUT', body:JSON.stringify(Object.fromEntries(new FormData(e.target))) }); $('#modal-root').innerHTML = ''; state.page = 'profile'; state.viewedUserId = state.auth.userId; render(); } catch (error) { toast(error.message); } }; } catch (error) { toast(error.message); } }
	function authModal(mode) { $('#modal-root').innerHTML = `<div class="modal-backdrop"><section class="modal"><h2>${mode === 'login' ? 'Sign in to Chirp' : 'Create your account'}</h2><form class="form" id="auth-form">${mode === 'register' ? '<div><label>Username</label><input name="username" minlength="3" maxlength="30" required></div><div><label>Email</label><input name="email" type="email" required></div><div><label>Display name</label><input name="displayName"></div>' : '<div><label>Username or email</label><input name="usernameOrEmail" required></div>'}<div><label>Password</label><input name="password" type="password" minlength="8" required></div><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">${mode === 'login' ? 'Sign in' : 'Register'}</button></div></form></section></div>`; $('#auth-form').onsubmit = async (e) => { e.preventDefault(); try { state.auth = await request(`/api/auth/${mode}`, { method:'POST', body:JSON.stringify(Object.fromEntries(new FormData(e.target))) }); localStorage.setItem('chirp_auth', JSON.stringify(state.auth)); $('#modal-root').innerHTML = ''; render(); } catch (error) { toast(error.message); } }; }
	function logout(show = true) { state.auth = null; localStorage.removeItem('chirp_auth'); render(); if (show) toast('Signed out'); }
	document.addEventListener('click', async (e) => { const b = e.target.closest('[data-action]'); if (!b) return; const a = b.dataset.action; if (a === 'auth') authModal(b.dataset.mode); if (a === 'close') $('#modal-root').innerHTML = ''; if (a === 'logout') logout(); if (a === 'home' || a === 'profile' || a === 'notifications') { state.page = a === 'home' ? 'home' : a; state.viewedUserId = a === 'profile' ? state.auth.userId : null; render(); } if (a === 'connections') { state.page = 'connections'; state.viewedUserId = b.dataset.userId; state.connectionType = b.dataset.type; render(); } if (a === 'back-profile') { state.page = 'profile'; render(); } if (a === 'view-profile') { state.page = 'profile'; state.viewedUserId = b.dataset.id; render(); } if (a === 'edit-profile') editProfile(); if (a === 'refresh') loadPage(); if (a === 'post') createPost(); if (a === 'like') toggleLike(b.dataset.id, b); if (a === 'comments') comments(b.dataset.id); if (a === 'follow') follow(b.dataset.id, b); if (a === 'delete' && confirm('Delete this post?')) { try { await request(`/api/users/${state.auth.userId}/posts/${b.dataset.id}`, { method:'DELETE' }); b.closest('.post').remove(); toast('Post deleted'); } catch (error) { toast(error.message); } } if (a === 'read-all') { try { await request(`/api/users/${state.auth.userId}/notifications/read-all`, { method:'PUT' }); toast('Notifications marked as read'); loadNotifications(); } catch (error) { toast(error.message); } } });
	let searchTimer;
	document.addEventListener('input', (e) => { if (e.target.id === 'post-content') { const n = e.target.value.length; $('#counter').textContent = `${n} / 280`; $('[data-action="post"]').disabled = !e.target.value.trim(); } if (e.target.id === 'search') { const query = e.target.value.trim(); clearTimeout(searchTimer); searchTimer = setTimeout(() => searchUsers(query), 250); } });
	async function searchUsers(query) { const target = $('#search-results'); if (!target) return; if (!query) { target.innerHTML = ''; return; } try { const results = await request(`/api/search/users?q=${encodeURIComponent(query)}`); const users = results.filter((item) => item.id != state.auth.userId).slice(0, 8); const states = await Promise.all(users.map((item) => request(`/api/users/${state.auth.userId}/follows/${item.id}/status`).catch(() => false))); target.innerHTML = results.length ? `<div class="search-results">${results.slice(0, 8).map((item, index) => `<div class="user-result">${avatar(item)}<button class="user-result-info" style="text-align:left;background:transparent" data-action="view-profile" data-id="${item.id}"><strong>${esc(item.displayName || item.username)}</strong><small>@${esc(item.username)}</small></button>${item.id == state.auth.userId ? '' : `<button class="follow-btn" data-action="follow" data-id="${item.id}" data-following="${Boolean(states[users.findIndex((u) => u.id == item.id)])}">${states[users.findIndex((u) => u.id == item.id)] ? 'Unfollow' : 'Follow'}</button>`}</div>`).join('')}</div>` : '<div class="search-results"><div style="padding:12px;color:var(--muted)">No users found</div></div>'; } catch (error) { target.innerHTML = `<div class="search-results"><div style="padding:12px;color:var(--danger)">${esc(error.message)}</div></div>`; } }
	render();
})();
