name: Twitter Clone API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: twitter_app
          POSTGRES_USER: twitteruser
          POSTGRES_PASSWORD: devpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start Spring Boot
        working-directory: backend
        run: |
          mvn spring-boot:run &
          sleep 30

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman
    
      - name: run api tests
        working-directory: tests/newman
        run: newman run general.postman_collection.json