name: Build and Run Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Run Docker Container
        run: docker run --rm my-app:latest
