name: Twitter Clone Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: docker build -t twitter-clone-backend:latest ./backend

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Wait for Backend
        run: |
          echo "Waiting for backend..."

          for i in {1..60}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health)

            if [ "$STATUS" = "200" ]; then
              echo "Backend is ready!"
              break
            fi

            echo "Backend status: $STATUS"
            sleep 2
          done

          curl -f http://localhost:8080/actuator/health

      - name: Show Docker Containers
        run: docker compose ps

      - name: Show Backend Logs
        if: always()
        run: docker compose logs backend

      - name: Run Newman API Tests
        run: |
          docker compose run --rm newman

      - name: Stop Docker Compose
        if: always()
        run: docker compose down